[
  {
    _id: "65a0158ab2c30fad25a229ed",
    id: 1,
    name: "Ceramic Teapot with Bamboo handle Removable Infuser for Flower and Loose Tea",
    img1: "http://localhost:4000/images/p1_1.jpg",
    img2: "http://localhost:4000/images/p1_2.jpg",
    img3: "http://localhost:4000/images/p1_3.jpg",
    type: "Teaware",
    category: "Ceramic",
    price: "2999",
    description:
      "Tea Pots Volume: 750 ml 25.3 oz large capacity. Environmentally Friendly Material: Classic ceramic teapots with gradient color! Made of iron-containing and pro-grade ceramic clay, It's Lead-Free and more durable. The grainy matte glazed is crafted by artisan's hand-sprayed, fired at high temperatures to achieve a long-lasting color. Comfortable Design: The embossing of mountains, rivers and oceans coexist harmoniously, with oriental bamboo wood handle, heat insulation and anti-scalding.It will become a work of art on your table!",
    rating: [
      5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
      5, 5, 5, 5, 5, 5,
    ],
    count: 1,
  },
  {
    _id: "65a0158ab2c30fad25a229ee",
    id: 2,
    name: "Steinzeit Design Tea Pot (44 oz) - Premium Ceramic Teapot with Infuser for Loose Tea",
    img1: "http://localhost:4000/images/p2_1.jpg",
    img2: "http://localhost:4000/images/p2_2.jpg",
    img3: "http://localhost:4000/images/p2_3.jpg",
    type: "Teaware",
    category: "Ceramic",
    price: "3999",
    description:
      "ROBUST CERAMIC - has better heat retention and is much more stable than fragile glass. Compared to stainless steel, ceramic does not absorb annoying odors.THE MATERIAL WONDER CERAMIC - is based on natural raw materials and is completely recyclable. This durable material is free of toxic substances and perfect for people and the environment. UNIQUE DESIGN - The impressive pattern of the matte black reactive glaze is created naturally during the firing process. This makes each teapot absolutely unique.",
    rating: [
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
    ],
    count: 3,
  },
  {
    _id: "65a0158ab2c30fad25a229ef",
    id: 3,
    name: "Porcelain Tea Set, Portable Gongfu Teapot Set with Tea Maker and Bag",
    img1: "http://localhost:4000/images/p3_1.jpg",
    img2: "http://localhost:4000/images/p3_2.jpg",
    img3: "http://localhost:4000/images/p3_3.jpg",
    type: "Teaware",
    category: "Porcelain",
    price: "3999",
    description:
      "Each tea set is made from selected natural high-grade kaolinite materials, fired at high temperatures, and finally carefully carved by craftsmen. The set allows the brewing to breathe freely with good sealing performance, to retain the original flavor and fragrance of tea. The surface of tea set is coated with a transparent glaze, green and safe, which prevents tea from penetrating into the interior of the tea sets. The pattern of each tea set is different and unique, which is naturally generated during the firing process. The Chinese tea set will bring you the unique visual experience.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a229f0",
    id: 4,
    name: "Stove Top Whistling Tea Kettle-Surgical Stainless Steel Teakettle Teapot",
    img1: "http://localhost:4000/images/p4_1.jpg",
    img2: "http://localhost:4000/images/p4_2.jpg",
    img3: "http://localhost:4000/images/p4_3.jpg",
    type: "Teaware",
    category: "Steel",
    price: "4999",
    description:
      "Ergonomically designed handle and push-button technology makes pouring a breeze! The combination of high-quality nylon material and stainless steel effectively insulates and avoids being scalded. Make tea for your entire family with this 3 Quart large kettle (MAX BOILING CAPACITY: 2.64 QT). The loud whistle allows to hear it from another room when the water is boiled, effectively reducing safety hazards and preventing over boiling. It is made of 5 layers encapsulated bottom, which improves heating performance while reducing heat loss, greatly shortening boiling time. It is compatible with all types of cooktops, including induction, gas, electric, halogen and radiant cooktops.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 5,
  },
  {
    _id: "65a0158ab2c30fad25a229f1",
    id: 5,
    name: "Whistling Tea Pots for Stove Top - Sleek Stainless Steel Stovetop Kettle",
    img1: "http://localhost:4000/images/p5_1.jpg",
    img2: "http://localhost:4000/images/p5_2.jpg",
    img3: "http://localhost:4000/images/p5_3.jpg",
    type: "Teaware",
    category: "Steel",
    price: "5999",
    description:
      "Inspired by morandi color, the color matching of tea kettle is soothing and elegant.  We also provide a free anti-scald pinch mitt, so you can handle the teakettle at ease. Made of food grade 18/8 stainless steel, makes it more rust and corrosion resistant. Thick body - 0.49mm, making it more durable and sturdy. 5-layer metal bottom with high thermal conductivity for more uniform heating and longer service life. Compatible with various cooktops including electric, gas, induction and so on.",
    rating: [
      5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
      5, 5, 5, 5, 5, 5, 5,
    ],
    count: 8,
  },
  {
    _id: "65a0158ab2c30fad25a229f2",
    id: 6,
    name: "Enamel on Steel Whistling Teakettle with Natural Wood handle, 1.4 quarts (Fog Grey)",
    img1: "http://localhost:4000/images/p6_1.jpg",
    img2: "http://localhost:4000/images/p6_2.jpg",
    img3: "http://localhost:4000/images/p6_3.jpg",
    type: "Teaware",
    category: "Steel",
    price: "6999",
    description:
      "Clean lines and natural wood help create a design that is distinctly northern European; the light color beautifully accents the enamel finish of the teakettle's body. The blonde wood handle and knob are made of 100% natural Rubberwood; the wood stays cool to the touch when boiling water. Chantal enamel is fired at high temperatures to create a smooth, glossy finish that is not to fade. One-piece body construction eliminates an interior seam and prevents rust; premium 'boiler' enamel on the interior provides extra durability.",
    rating: [
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
    ],
    count: 5,
  },
  {
    _id: "65a0158ab2c30fad25a229f3",
    id: 7,
    name: "Tea Kettle for Stovetop, 2.1 Quart Loud Whistle,Food Grade Stainless Steel",
    img1: "http://localhost:4000/images/p7_1.jpg",
    img2: "http://localhost:4000/images/p7_2.jpg",
    img3: "http://localhost:4000/images/p7_3.jpg",
    type: "Teaware",
    category: "Steel",
    price: "7999",
    description:
      "The water kettle teapot has a capacity of 2.1 Quart. Professional food-grade finish and stainless steel workmanship ensure this jug is rust and corrosion resistant. When you are simultaneously focused on other issues (such as chores or games), the tea kettle will alert you with a loud whistle after boiling water, effectively reducing safety hazards and preventing boiling. The silicone coated handle is effectively insulated, the ergonomic shape and design adds comfort for pouring and filling.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 10,
  },
  {
    _id: "65a0158ab2c30fad25a229f4",
    id: 8,
    name: "Stovetop Safe Japanese Cast Iron Tea Kettle, Diamond Design with Removable Infuser",
    img1: "http://localhost:4000/images/p8_1.jpg",
    img2: "http://localhost:4000/images/p8_2.jpg",
    img3: "http://localhost:4000/images/p8_3.jpg",
    type: "Teaware",
    category: "Cast Iron",
    price: "2999",
    description:
      "Shine Bright Like A Diamond - Serve for 2-3 people, 3-4 cups when the water of the teapot is filled to the top. The stovetop safe cast iron tea kettle allows gradual and even heating. It will help infuse the greatest amount of flavor from the loose tea into the water. Japanese Cast iron teapot has long heat preservation and could break down the elements of Fe2+, which is beneficial to your body. Note: As a Teapot - VOLUME: 30 oz. As a Tea Kettle on stove top - BOILING CAPACITY: 24 oz.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 1,
  },
  {
    _id: "65a0158ab2c30fad25a229f5",
    id: 9,
    name: "Stovetop Safe Cast Iron Tea Kettle, Wave Design Coated with Enameled Interior for 30 oz",
    img1: "http://localhost:4000/images/p9_1.jpg",
    img2: "http://localhost:4000/images/p9_2.jpg",
    img3: "http://localhost:4000/images/p9_3.jpg",
    type: "Teaware",
    category: "Cast Iron",
    price: "3999",
    description:
      "Teapot FULL-LOAD CAPACITY: 30 oz / 900 ml, RECOMMENDED BOILING CAPACITY: 24 oz / 700 ml. The cast iron teapot allows gradual and even heating. It will help infuse the greatest amount of flavor from the tea leaves into the water. Cast iron teapot could break down the elements of Fe2+, which is beneficial to your body. Japanese cast iron teapot also has long heat preservation.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 2,
  },
  {
    _id: "65a0158ab2c30fad25a229f6",
    id: 10,
    name: "Cast Iron Teapot with 4 Tea Cups Trivet Tetsubin Tea Kettle with Infuser",
    img1: "http://localhost:4000/images/p10_1.jpg",
    img2: "http://localhost:4000/images/p10_2.jpg",
    img3: "http://localhost:4000/images/p10_3.jpg",
    type: "Teaware",
    category: "Cast Iron",
    price: "4999",
    description:
      "Selected from RAW IRON, undergone 1500 ℃ high temperature melting,casting,and burning above 5 hours, Tovacu cast iron teapot is hard and durable.Iron teapot was recognized to be a best kitchenware to boil water due to its SWEET and SOFT water flavour and Fe2+ release,which supplement human’s Iron needed and prevent anemia.In additions, Cast iron tea set is suitable for cooking various teas such as fruit tea, black tea, Pu'er tea.",
    rating: [
      5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
      5, 5, 5, 5, 5, 5, 5,
    ],
    count: 3,
  },
  {
    _id: "65a0158ab2c30fad25a229f7",
    id: 11,
    name: "Kungfu Magic Deer Tea Set Glass Magnetic Teapot Semi-Automatic Water Guide",
    img1: "http://localhost:4000/images/p11_1.jpg",
    img2: "http://localhost:4000/images/p11_2.jpg",
    img3: "http://localhost:4000/images/p11_3.jpg",
    type: "Teaware",
    category: "Glass",
    price: "5999",
    description:
      "This elegant magic teapot is composed of clear borosilicate glass, which can endure temperatures ranging from -20°C to 151°C, is not easily cracked, and has outstanding heat resistance and durability, making it suitable for brewing blossoming tea. Magic deer tea pot features an exquisite blue ceramic deer as the base of the pot, with golden textured decorations that give it a more luxurious appearance. magic teapot specially designed goose-neck style drip-free spout allows for smooth water flow",
    rating: [
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
    ],
    count: 4,
  },
  {
    _id: "65a0158ab2c30fad25a229f8",
    id: 12,
    name: "Glass Teapot, Heat Resistant, Stainless Steel Infuser, Borosilicate Glass",
    img1: "http://localhost:4000/images/p12_1.jpg",
    img2: "http://localhost:4000/images/p12_2.jpg",
    img3: "http://localhost:4000/images/p12_3.jpg",
    type: "Teaware",
    category: "Glass",
    price: "6999",
    description:
      "Glass Teapot is handmade, has a Stylish Design and an Ergonomic Handle. All metal parts of the Glass Teapot are made of Stainless Steel and can be easily removed for easy maintenance. Fine mesh Tea Strainer contributes to fast tea brewing and keeps most of the tea leaves from getting into the beverage. The spout of the teapot has a special Non-Drip style. An ergonomically designed handle gives you a sturdy grip, pour and fill. The teapot volume is 1100 ml/37 oz which is enough for 5 cups of tea",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 5,
  },
  {
    _id: "65a0158ab2c30fad25a229f9",
    id: 13,
    name: "Stovetop & Microwave Safe Teapot (40 oz) with Removable Loose Tea Infuser",
    img1: "http://localhost:4000/images/p13_1.jpg",
    img2: "http://localhost:4000/images/p13_2.jpg",
    img3: "http://localhost:4000/images/p13_3.jpg",
    type: "Teaware",
    category: "Glass",
    price: "7999",
    description:
      "The Celebration Teapot’s simple, clean lines and perfect proportions blend beautifully with any décor. Constructed of the highest-quality materials for years of enjoyment, this is the “little black dress” of teapots. Each part of the Celebration Teapot is crafted of high quality heat-resistant borosilicate glass – making it stovetop, microwave and dishwasher safe. With this premium borosilicate glass tea pot and infuser for loose tea all you taste is pure, delicious tea.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 6,
  },
  {
    _id: "65a0158ab2c30fad25a229fa",
    id: 14,
    name: "Garden Ceramic Tea Mug with Infuser and Lid Tea Mugs Wooden Handle 14 ounces",
    img1: "http://localhost:4000/images/p14_1.jpg",
    img2: "http://localhost:4000/images/p14_2.jpg",
    img3: "http://localhost:4000/images/p14_3.jpg",
    type: "Teaware",
    category: "Ceramic",
    price: "2999",
    description:
      "Ceramic filter and lid, filter is healthier and tastes better than the stainless steel filter. The filter can be removed and can be washed by hand or dishwasher for easy cleaning. The lid coaster just fits the size of the tea infuser when you put it up.Also it can help to keep the tea heat when you put the lid on the mug. The handle is made of wood and the handle will leave more space for your hand during the process of taking the cup to prevent your hand from being scalded.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a229fb",
    id: 15,
    name: "Yixing Teapot Pure Manual Pot of Thick Mouth Coarse Ore Purple Clay Teapot",
    img1: "http://localhost:4000/images/p15_1.jpg",
    img2: "http://localhost:4000/images/p15_2.jpg",
    img3: "http://localhost:4000/images/p15_3.jpg",
    type: "Teaware",
    category: "Clay",
    price: "3999",
    description:
      "Exquisite workmanship and design, smooth and comfortable surface, perfect for your tea ceremony! Suitable size, easy to carry, thick foam pads, easy storage. The beautiful details of this traditional Chinese craft will bring beauty and elegance to your living room or office. It can keep the color, fragrance and taste of tea for a long time.",
    rating: [
      5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
      5, 5, 5, 5, 5, 5, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a229fc",
    id: 16,
    name: "Kungfu Clay Portable Travel Tea Sets, Tea Canister, 4 Teacups,Tea Mat and Travel Bag",
    img1: "http://localhost:4000/images/p16_1.jpg",
    img2: "http://localhost:4000/images/p16_2.jpg",
    img3: "http://localhost:4000/images/p16_3.jpg",
    type: "Teaware",
    category: "Clay",
    price: "4999",
    description:
      "Portable Tea Sets Design are packaged into lightweight travel bag that can be easy and convenient to carry out. perfect for family gathering or friends gathering. Tea sets are using thousand years of Chinese pottery making craft to creating extraordinary quality. It's made of durable & high quality purple clay and under 1380 ℃ high temperature fire, which is smooth and easy to clean.",
    rating: [
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a229fd",
    id: 17,
    name: "Tai chi bagua Teapot Set 12Oz Chinese Zisha Clay Pottery ",
    img1: "http://localhost:4000/images/p17_1.jpg",
    img2: "http://localhost:4000/images/p17_2.jpg",
    img3: "http://localhost:4000/images/p17_3.jpg",
    type: "Teaware",
    category: "Clay",
    price: "5999",
    description:
      "zisha clay raw ore qingshui mud and Green mud, purple sand,zisha raw ore.Add only air and water, healthy and eco-friendly. Capacity: Each pot of 180 ml .suitable for one or two people drinking; Limited production of manual, clear seal, with collection value. Beautiful, hand-made, Chinese traditional tai chi modeling design，Two lid decorated with tai chi eight diagrams on the tai chi Yin Yang pot, elegant appearance.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a229fe",
    id: 18,
    name: "Tea Set for 6, Kiln Altered Glaze Porcelain Tea Set with 1 Teapot, 6 Tea Cups & 1 Tea Tray",
    img1: "http://localhost:4000/images/p18_1.jpg",
    img2: "http://localhost:4000/images/p18_2.jpg",
    img3: "http://localhost:4000/images/p18_3.jpg",
    type: "Teaware",
    category: "Porcelain",
    price: "6999",
    description:
      "Mysterious & Unique, Just Like You: This tea set displays a mysterious dark blue pattern with a hint of purple. As the colors blend within the kiln, the glow around the spots reveals subtle differences between each other, irreplaceable and unique. When you serve your guests, friends, or family with this special tea set, you will hear non-stop compliments on your taste. You will not only be drinking fragrant tea, but also savoring an unforgettable visual treat.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a229ff",
    id: 19,
    name: "Portable Gongfu Tea Set with Infuser and Gift Bag - Floral Blue",
    img1: "http://localhost:4000/images/p19_1.jpg",
    img2: "http://localhost:4000/images/p19_2.jpg",
    img3: "http://localhost:4000/images/p19_3.jpg",
    type: "Teaware",
    category: "Porcelain",
    price: "7999",
    description:
      "Tao of Tea is a simple and insightful ceremony, as the special black edition, the minimalism design and ancient Chinese cup style is a greeting to Chinese Tea Tao. To reinforce the texture, we choose a frosted surface for better tactile. The wooden handle could avoid hot water spillage, and the hidden strainer in the teapot could effectively make tea leaves stay inside the pot.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a00",
    id: 20,
    name: "Chinese Gongfu Tea Set, Dragon Shape, with 360Rotating Teapot and Infuser",
    img1: "http://localhost:4000/images/p20_1.jpg",
    img2: "http://localhost:4000/images/p20_2.jpg",
    img3: "http://localhost:4000/images/p20_3.jpg",
    type: "Teaware",
    category: "Chinese",
    price: "2999",
    description:
      "Create a tea set with Chinese characteristic culture, with a unique Kung Fu color, and the tea tasted out of the way. The appearance is noble and elegant, and it can be placed in the home, office or balcony, which can greatly improve the grade. Traditional Craft: After 1250 ℃ to 1400 ℃ high temp fire and form, use one thousand years of Chinese pottery making craft, choose quality raw materials, creating extraordinary quality. With superb skills, we choose high quality raw materials,creating extraordinary quality.",
    rating: [
      5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
      5, 5, 5, 5, 5, 5, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a01",
    id: 21,
    name: "Glass Magnetic Tea Pot,Lazy Kungfu Drip Teapot with Infuser",
    img1: "http://localhost:4000/images/p21_1.jpg",
    img2: "http://localhost:4000/images/p21_2.jpg",
    img3: "http://localhost:4000/images/p21_3.jpg",
    type: "Teaware",
    category: "Chinese",
    price: "3999",
    description:
      "This elegant magic teapot is made of clear borosilicate glass, which can endure temperatures ranging from -20°C to 150°C, is not easily cracked, and has outstanding heat resistance and durability, making it suitable for brewing blossoming tea. Suitable for a variety of scenarios. This is a fully functional magnetic tea pot with details and artistic decorations that set it apart from other drip teapot. As a lazy kungfu drip teapot, it is suitable for home leisure, office, or outdoor camping, making it a great choice",
    rating: [
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a02",
    id: 22,
    name: "Traditional Chinese Teapot with Stainless Infuser, Beautiful Asian Teapot ",
    img1: "http://localhost:4000/images/p22_1.jpg",
    img2: "http://localhost:4000/images/p22_2.jpg",
    img3: "http://localhost:4000/images/p22_3.jpg",
    type: "Teaware",
    category: "Chinese",
    price: "4999",
    description:
      "Beautiful Japanese Countryside in Golden: This tea pot is perfect for enjoying your tea time. Classic and exquisite. Drinking tea with this tea pot is just like holding the beauty of distant Japanese style in your hands. Focus on Details for Your Better Feelings: The handle of the teapot adopts Traditional HEMP ROPE, retro and anti-hot, you will feel comfortable when gripping it. Built-in density stainless filter, helps tea separate well, you can drink conveniently. A smooth spout helps water flows smoothly.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a03",
    id: 23,
    name: "Ceramic Tea set with Infuser, Bentwood Handle",
    img1: "http://localhost:4000/images/p23_1.jpg",
    img2: "http://localhost:4000/images/p23_2.jpg",
    img3: "http://localhost:4000/images/p23_3.jpg",
    type: "Teaware",
    category: "Japanese",
    price: "5999",
    description:
      "Contemporary Japanese Tea Set-This minimalist japanese teapot set design with slightly flat cobblestone shape by nature and has a matte smooth touching glazed, brimmed with oriental flavor giving you a feeling of peaceful and harmony vividly. definitely great teapot to own or for entertaining guests elegantly.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a04",
    id: 24,
    name: "Japanese Gongfu Tea Set, Ceramic Portable Tea Set, 13-piece Withgrey Leather Case",
    img1: "http://localhost:4000/images/p24_1.jpg",
    img2: "http://localhost:4000/images/p24_2.jpg",
    img3: "http://localhost:4000/images/p24_3.jpg",
    type: "Teaware",
    category: "Japanese",
    price: "6999",
    description:
      "Suitable for brewing different kinds of tea, like black tea, Pu-er, Oolong, Green Tea, and even tea bag. The tea set is made with high-quality materials that are durable and easy to clean. Red Orange appearance. Each cup has a unique design and is comfortable to hold. The teapot has a removable strainer that filters tea leaves for a smooth and enjoyable drinking experience",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a05",
    id: 25,
    name: "Japanese Tea Set Teal with White Plum-Flower Ceramic Tetsubin Teapot",
    img1: "http://localhost:4000/images/p25_1.jpg",
    img2: "http://localhost:4000/images/p25_2.jpg",
    img3: "http://localhost:4000/images/p25_3.jpg",
    type: "Teaware",
    category: "Japanese",
    price: "6999",
    description:
      "Tea cup set is traditional style and stylish design, elegant handcrafted 5 sets tea pot, great for tea brewing, blooming tea, loose tea, herbal tea, Chinese kung fu tea, rose tea, blossom loose leaf & flowers, and flowering tea blooms. This tea set features a 27 fl oz teapot, four 5 fl oz cups. The teapots handle is made of bamboo which is very comfortable to hold with your hand to brew all kinds of tea easily",
    rating: [
      5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
      5, 5, 5, 5, 5, 5, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a06",
    id: 26,
    name: "Portable Japanese Tea Set, Charcoal Grey Travel Porcelain Tea Set",
    img1: "http://localhost:4000/images/p26_1.jpg",
    img2: "http://localhost:4000/images/p26_2.jpg",
    img3: "http://localhost:4000/images/p26_3.jpg",
    type: "Teaware",
    category: "Japanese",
    price: "7999",
    description:
      "Unique and exquisite design: Our Japanese tea set features a distinctive and sophisticated design. The outer glaze is a black-grey stone finish, providing a visually stunning and high-end look. The smooth and comfortable texture enhances the tactile experience. The inner glaze is transparent, allowing for easy cleaning and reflecting the true color of the tea. It offers tea enthusiasts an excellent tool for tea leaf identification.",
    rating: [
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
      4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8, 4.8,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a07",
    id: 27,
    name: "10 oz Golden Hand Print Tea Cup And Bamboo Saucer Set TCS19 (Black)",
    img1: "http://localhost:4000/images/p27_1.jpg",
    img2: "http://localhost:4000/images/p27_2.jpg",
    img3: "http://localhost:4000/images/p27_3.jpg",
    type: "Teaware",
    category: "Accessories",
    price: "2999",
    description:
      "Crafted with quality porcelain to retain heat to keep tea warm longer. Beautiful Gold-Plated Handle and white lightning design. This tea cups has an easy-grip golden handle to increase the comfort of use.Wood base to hold the cup,look beautiful appearance. Capacity: 10 OZ. Dishwasher-safe, Non-microwavable.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a08",
    id: 28,
    name: "Matcha Tea Set, Bowl, Bamboo Whisk, Scoop, Sifter, Whisk Holder, Stand",
    img1: "http://localhost:4000/images/p28_1.jpg",
    img2: "http://localhost:4000/images/p28_2.jpg",
    img3: "http://localhost:4000/images/p28_3.jpg",
    type: "Teaware",
    category: "Accessories",
    price: "3999",
    description:
      "HIGH QUALITY BAMBOO WHISK: Our pronged whisk handcrafted about 76 fine tines, engineered to create optimal agitation and it’s crafted in the perfect shape to whisk, blend effectively, and froth perfectly whisk up a frothy cup of tea. Same color for matcha bowls & whisk holder, higher sense of ceremony. Impress your loved one by sharing a kit that allows them to prepare the most ly beneficial drink in the world!",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a09",
    id: 29,
    name: "Tea Strainer, Tea Filter, Gold Copper for Tea Maker Loose Leaf Teas",
    img1: "http://localhost:4000/images/p29_1.jpg",
    img2: "http://localhost:4000/images/p29_2.jpg",
    img3: "http://localhost:4000/images/p29_3.jpg",
    type: "Teaware",
    category: "Accessories",
    price: "2999",
    description:
      "Long handle design, easy to hold, not easy to burn hand when pouring tea. The tea drain is a good utensil used to enhance the tea soup. Ideal tool for making tea. Good finish, fine and dense mesh, corrosion resistance, no rust and good slag separation effect.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a0a",
    id: 30,
    name: "Japanese Sakura and Pattern Coaster Tea Cup Holder Absorbent Stone Cork Base Set",
    img1: "http://localhost:4000/images/p30_1.jpg",
    img2: "http://localhost:4000/images/p30_2.jpg",
    img3: "http://localhost:4000/images/p30_3.jpg",
    type: "Teaware",
    category: "Accessories",
    price: "2999",
    description:
      "Round-shaped square-shaped design ; -Special absorbent ceramic stone: absorb the water outside the icy glass easily; -Cork on the back: protect the desktop from scratches and provide additional gripping on the desk ; -Suits all types of drinking glass; -Take this mug coaster as for the best prevention of slipping and enjoy your perfect drinking experience.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a0b",
    id: 31,
    name: "earl grey moonlight",
    img1: "http://localhost:4000/images/p31_1.jpg",
    img2: "http://localhost:4000/images/p31_2.jpg",
    img3: "http://localhost:4000/images/th1.jpeg",
    type: "Tea",
    category: "Black",
    price: "300",
    description:
      "By popular demand, we created this Earl Grey 'cream' blend. Comforting flavors of vanilla and cream combine to soften the citrus notes of traditional Earl Grey. Your taste buds will swoon at first sip of our Earl Grey Moonlight.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a0c",
    id: 32,
    name: "yunnan noir",
    img1: "http://localhost:4000/images/p32_1.jpg",
    img2: "http://localhost:4000/images/p32_2.jpg",
    img3: "http://localhost:4000/images/th2.jpeg",
    type: "Tea",
    category: "Black",
    price: "400",
    description:
      "Yunnan Noir is a black tea from the Yunnan province of China, the birthplace of tea itself. Much of the tea in this southern province is a large leaf variety. Grown at 1500 meters above sea level where the mountains are veiled in mist, with clean water and rich soil form ideal growing conditions and contribute to the unique flavor.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a0d",
    id: 33,
    name: "black dragon pearls",
    img1: "http://localhost:4000/images/p33_1.jpg",
    img2: "http://localhost:4000/images/p33_2.jpg",
    img3: "http://localhost:4000/images/th3.jpeg",
    type: "Tea",
    category: "Black",
    price: "500",
    description:
      "Black Dragon Pearls is a rare, hand-rolled variety of black tea with a smooth, rich and chocolatey taste. Hailing from the Yunnan province, this black tea version of the popular Dragon Pearl is comprised of only the highest quality leaves and buds expertly rolled into a large pearl-like shape. Black Dragon Pearls are naturally sweet and smooth, with a touch of earthiness. Subtle cocoa notes whisper gently as each pearl unfurls, delivering a superior tea experience not to be missed. We suggest using 2-3 pearls per cup for the fullest flavor.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a0e",
    id: 34,
    name: "golden needle yunnan",
    img1: "http://localhost:4000/images/p34_1.jpg",
    img2: "http://localhost:4000/images/p34_2.jpg",
    img3: "http://localhost:4000/images/th4.jpeg",
    type: "Tea",
    category: "Black",
    price: "600",
    description:
      "Grown high in the mountains of Simao, Pu'er, Yunnan, China, this tea has a striking appearance. The leaves are stick straight, roughly 1.5 to 2 inches long, and range from deep dark brown to a vivid gold. Also striking is the complexity of the cup. Offering a medium bodied liquor with notes of spice, cocoa, and hints of wildflower honey, this tea grown from the 'Snow Buds #100' cultivar, known for its big downy buds. Careful shaping and oxidation result in a smooth, delicious brew and an impressive presentation.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a0f",
    id: 35,
    name: "masala chai",
    img1: "http://localhost:4000/images/p35_1.jpg",
    img2: "http://localhost:4000/images/p35_2.jpg",
    img3: "http://localhost:4000/images/th5.jpeg",
    type: "Tea",
    category: "Flavoured",
    price: "300",
    description:
      "Our Masala Chai tea blend combines premium Ceylon black tea with cinnamon, cardamom, cloves and ginger. In Indian culture, 'Masala' means 'a blend of spices', and 'chai' simply means 'tea.' So, Masala Chai is literally 'spiced tea'. Our interpretation tries to stay true to its definition thanks to a warm and inviting fragrance, zesty flavor, and invigorating, aromatic finish. We suggest two heaping teaspoons per 8 oz cup. Sugar or milk if desired.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a10",
    id: 36,
    name: "ayurvedic chai",
    img1: "http://localhost:4000/images/p36_1.jpg",
    img2: "http://localhost:4000/images/p36_2.jpg",
    img3: "http://localhost:4000/images/th6.jpeg",
    type: "Tea",
    category: "Flavoured",
    price: "400",
    description:
      "For those days when you're feeling a bit adventurous, steep a cup of this exotic, yet subtle twist on classic chai. We've taken the delicate flavor of white tea and blended it with familiar chai flavors and the added zesty notes of lemongrass, coconut and pineapple. Steep this aromatic beauty for a complex cup of fruit and spice that leaves the alluring essence of cinnamon dancing in its wake.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a11",
    id: 37,
    name: "mindful mint chai",
    img1: "http://localhost:4000/images/p37_1.jpg",
    img2: "http://localhost:4000/images/p37_2.jpg",
    img3: "http://localhost:4000/images/th7.jpeg",
    type: "Tea",
    category: "Flavoured",
    price: "500",
    description:
      "Mindful Mint Chai is a blend of mind cooling spearmint and heartwarming spices with toasty hojicha green tea to balance your whole self. Cozy yet reviving, this tea is a low-caffeine way to stay engaged and grounded. Perfect for those moments when you need to both perk up and settle down. Great straight up but also delightful in a latte.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a12",
    id: 38,
    name: "gaucho mate chai",
    img1: "http://localhost:4000/images/p38_1.jpg",
    img2: "http://localhost:4000/images/p38_2.jpg",
    img3: "http://localhost:4000/images/th8.jpeg",
    type: "Tea",
    category: "Flavoured",
    price: "600",
    description:
      "East meets west in this culture mash-up chai blend. Our Brazil grown toasted mate is blended with masala spices for some sweet heat and toasty flavor. Named to honor the rugged cattlemen of the South American pampas, our Gaucho Mate Chai is sure to become a fireside favorite.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a13",
    id: 39,
    name: "mango",
    img1: "http://localhost:4000/images/p39_1.jpg",
    img2: "http://localhost:4000/images/p39_2.jpg",
    img3: "http://localhost:4000/images/th9.jpeg",
    type: "Tea",
    category: "Fruit",
    price: "300",
    description:
      "Our bestselling Mango black tea blend combines the citrusy quality of fine Ceylon black tea with the flavor of perfectly ripened mangoes. Juicy texture, creamy-dry finish with great floral aromatics and candy sweetness.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a14",
    id: 40,
    name: "blood orange",
    img1: "http://localhost:4000/images/p40_1.jpg",
    img2: "http://localhost:4000/images/p40_2.jpg",
    img3: "http://localhost:4000/images/th10.jpeg",
    type: "Tea",
    category: "Fruit",
    price: "400",
    description:
      "The blood orange is a culinary favorite, with its deep vibrant color and sweet, tangy flavor. A perfect ingredient for a refreshing herbal blend! Our Blood Orange tea pairs blood orange peels with hibiscus flowers and rose hips for a naturally sweet, caffeine-free flavor. Rich, hearty and tangy, with a good balance of orange peel dryness and fruit juiciness.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a15",
    id: 41,
    name: "wild strawberry",
    img1: "http://localhost:4000/images/p41_1.jpg",
    img2: "http://localhost:4000/images/p41_2.jpg",
    img3: "http://localhost:4000/images/th1.jpeg",
    type: "Tea",
    category: "Fruit",
    price: "500",
    description:
      "Even when the strawberry harvest is waning for the year, our Wild Strawberry herbal blend will have you smiling like the first pick of the season. Fresh strawberries, apple pieces, hibiscus flowers, and rose hips create a mellow, almost dessert-like tea. Sweet strawberry and sugared rhubarb aroma, beautiful warm berry color, pleasantly aromatic and not super sweet. A caffeine-free cup of pure delight.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a16",
    id: 42,
    name: "berry creme compote",
    img1: "http://localhost:4000/images/p42_1.jpg",
    img2: "http://localhost:4000/images/p42_2.jpg",
    img3: "http://localhost:4000/images/th2.jpeg",
    type: "Tea",
    category: "Fruit",
    price: "600",
    description:
      "Tangy-sweet spring berry blend with a hint of creme. Blackberry, blueberry and strawberry flavors party playfully in your cup like a rich berry compote with a dollop of cream. Party on! Our natural creme flavor is vegan-friendly and doesn't contain any dairy ingredients.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a17",
    id: 43,
    name: "milk oolong",
    img1: "http://localhost:4000/images/p43_1.jpg",
    img2: "http://localhost:4000/images/p43_2.jpg",
    img3: "http://localhost:4000/images/th3.jpeg",
    type: "Tea",
    category: "Oolong",
    price: "300",
    description:
      "Milk Oolong is a relatively new cultivar in the delicious world of Taiwanese teas and is prized for its inherent cream and butter notes. Lower quality versions have these notes enhanced through aromatization but the finest, true Milk Oolongs offer lightly roasted, rolled leaves that yield a light-bodied cup with sweet buttery texture and delicate floral aroma. Also called Jin Xuan or Golden Lily, it is ideal for multiple infusions and a dedicated Yixing teapot.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a18",
    id: 44,
    name: "fujian ti kuan yin",
    img1: "http://localhost:4000/images/p44_1.jpg",
    img2: "http://localhost:4000/images/p44_2.jpg",
    img3: "http://localhost:4000/images/th4.jpeg",
    type: "Tea",
    category: "Oolong",
    price: "400",
    description:
      "Ti Kuan Yin (also spelled Tieguanyin) is a legendary tea from the Fujian province and is one of China's most beloved oolongs. This loosely-rolled, lightly-oxidized (almost green) tea yields a pale-gold cup with a soft, buttery texture and orchid notes that linger to reveal the leaves' complexity. As the liquor cools, it reveals a sweet finish of honeydew melons.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a19",
    id: 45,
    name: "coconut grove pouchong",
    img1: "http://localhost:4000/images/p45_1.jpg",
    img2: "http://localhost:4000/images/p45_2.jpg",
    img3: "http://localhost:4000/images/th5.jpeg",
    type: "Tea",
    category: "Oolong",
    price: "500",
    description:
      "Time to break out the grass skirts and tiny umbrellas because our Coconut Grove Pouchong will have you feeling like you're dancing on an island beach. Our velvety smooth pouchong lays the perfect foundation for the tropical flavor of coconut to shine. It's like summer in a cup any time of year!",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a1a",
    id: 46,
    name: "silver needle",
    img1: "http://localhost:4000/images/p46_1.jpg",
    img2: "http://localhost:4000/images/p46_2.jpg",
    img3: "http://localhost:4000/images/th6.jpeg",
    type: "Tea",
    category: "White",
    price: "600",
    description:
      "Silver Needle (or Bai Hao Yin Zhen) is one of the most revered of Chinese teas, produced in the Fuding and Zhenhe districts of its Fujian province. Gathered only for a few days in early spring, the dedication to perfection is evident in the pale, ivory-colored liquor. The lingering fragrance of our Silver Needle is delicately honeysuckle floral, with a warmed sugar sweetness and a subtle hint of white grapes. Silver Needle feels refreshing, soft and airy on the palate. This is a high-grade Bai Hao version of this exquisite tea, perfect to enjoy in multiple infusions.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a1b",
    id: 47,
    name: "buddha's dream",
    img1: "http://localhost:4000/images/p47_1.jpg",
    img2: "http://localhost:4000/images/p47_2.jpg",
    img3: "http://localhost:4000/images/th7.jpeg",
    type: "Tea",
    category: "White",
    price: "300",
    description:
      "A tea worthy of meditating over, Buddha's Blend combines all of the elements needed to reach palate paradise. A soft blend of white and green tea, with accents of floral, fruit flavors this is a contemplative tea that is sure to bring a bit of enlightenment to your day.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a1c",
    id: 48,
    name: "white pearls",
    img1: "http://localhost:4000/images/p48_1.jpg",
    img2: "http://localhost:4000/images/p48_2.jpg",
    img3: "http://localhost:4000/images/th8.jpeg",
    type: "Tea",
    category: "White",
    price: "400",
    description:
      "These lovely pearls are made from white peony leaves that are hand-shaped. Each pearl is of the larger variety, weighing on average 3.5 to 4 grams. Once steeped, the cup reveals classic white peony notes of melon and cucumber, a little mineral flintiness and just a hint of honey. Perfect for on-the-road brewing and multiple steepings.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a1d",
    id: 49,
    name: "sencha premier",
    img1: "http://localhost:4000/images/p49_1.jpg",
    img2: "http://localhost:4000/images/p49_2.jpg",
    img3: "http://localhost:4000/images/th9.jpeg",
    type: "Tea",
    category: "Green",
    price: "500",
    description:
      "Steamed green tea from the Shizuoka prefecture of Japan, harvested in the early spring (the first flush). Sencha is one of Japan's most popular and beloved teas. The higher grades, like our Sencha Premier, tend to have more delicate flavor profiles. A crisp and clean cup with notes of freshly steamed edamame. Refreshing, sweet, and much more delicate than most Senchas. If you're new to Sencha (and the vibrant teas of Japan in general), this would be a great place to start.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a1e",
    id: 50,
    name: "dragonwell",
    img1: "http://localhost:4000/images/p50_1.jpg",
    img2: "http://localhost:4000/images/p50_2.jpg",
    img3: "http://localhost:4000/images/th10.jpeg",
    type: "Tea",
    category: "Green",
    price: "600",
    description:
      "Dragonwell (Lung Ching or Longjing in local parlance) is one of China's most famous green teas, originating from Hangzhou in Zhejiang province. This tea has a very distinctive shape: smooth and perfectly flattened along the inside vein of the leaf, the result of highly skilled shaping in a hot wok. This process, known as pan-firing or pan-frying, was perfected in China by tea masters over many centuries. It gives the tea an inviting, toasty aroma. Our fine Dragonwell green tea also has a sweet, rounded flavor, perhaps reminiscent of freshly roasted white corn. Full, nutty and buttery texture, and pleasantly dry finish. A truly satisfying cup of tea.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a1f",
    id: 51,
    name: "gyokuro",
    img1: "http://localhost:4000/images/p51_1.jpg",
    img2: "http://localhost:4000/images/p51_2.jpg",
    img3: "http://localhost:4000/images/th1.jpeg",
    type: "Tea",
    category: "Green",
    price: "300",
    description:
      "Gyokuro, a shade-grown steamed green tea, is among the finest of Japanese teas. While the young leaves of the spring season develop, the Gyokuro plants are shaded from the sun for several weeks. This slows the growth allowing tea leaves more time to develop depth and flavor. The sun-deprived leaves are higher in chlorophyll, which explains their vivid green color. They're also higher in amino acids, most notably L-theanine, which accounts for the perfectly smooth, rich and soft flavor.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a20",
    id: 52,
    name: "matcha",
    img1: "http://localhost:4000/images/p52_1.jpg",
    img2: "http://localhost:4000/images/p52_2.jpg",
    img3: "http://localhost:4000/images/th2.jpeg",
    type: "Tea",
    category: "Green",
    price: "400",
    description:
      "Matcha, the focal point of the Japanese Tea Ceremony, is a fine powder made by grinding green tea leaves. Only the finest, young, shade-grown gyokuro tea leaves are used to create matcha. The leaves are plucked and laid out flat to dry. Veins are removed and the leaves, now called tencha, are carefully ground in granite mills until they become the precious powder.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a21",
    id: 53,
    name: "chamomile",
    img1: "http://localhost:4000/images/p53_1.jpg",
    img2: "http://localhost:4000/images/p53_2.jpg",
    img3: "http://localhost:4000/images/th3.jpeg",
    type: "Tea",
    category: "Flower",
    price: "500",
    description:
      "Our Chamomile tea is made of the finest chamomile flowers from the Nile River Valley in Egypt. Considered a remedy for all ills by the ancient Egyptians, this golden herb remains a modern favorite to promote calm and relieve anxiety. When steeped, these fragrant chamomile blossoms smell of freshly cut apples and produce a rich, golden cup with calming flavor and sweet, floral finish. Our Chamomile tea is made with whole flower pieces and produces a delicious, caffeine-free infusion. It may also be served with a dash of honey.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a22",
    id: 54,
    name: "bella luna blue",
    img1: "http://localhost:4000/images/p54_1.jpg",
    img2: "http://localhost:4000/images/p54_2.jpg",
    img3: "http://localhost:4000/images/th4.jpeg",
    type: "Tea",
    category: "Flower",
    price: "600",
    description:
      "Experience the elusive mystery that is the phenomenon known as our Bella Luna Blue. Available only on days of a blue moon, our rare Bella Luna Blue blends the zesty freshness of lemongrass and the flavor of blueberries with the exotic Butterfly Pea Flower, which when brewed, turns this mystifying herbal tea indigo! For an even more exciting treat, add a few drops of lemon juice to the mix and watch as the real magic unfolds right before your eyes!",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a23",
    id: 55,
    name: "summer rose",
    img1: "http://localhost:4000/images/p55_1.jpg",
    img2: "http://localhost:4000/images/p55_2.jpg",
    img3: "http://localhost:4000/images/th5.jpeg",
    type: "Tea",
    category: "Flower",
    price: "300",
    description:
      "Our Summer Rose tea invokes the sweet lingering fragrance of late summer roses winding up a garden trellis. Mellow and deliciously floral, this rose tea is balanced with the bright briskness of a Ceylon black tea. Served hot or iced, it will bring to mind green lawns, porch swings and sunny warm days.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a24",
    id: 56,
    name: "jasmine phoenix pearls",
    img1: "http://localhost:4000/images/p56_1.jpg",
    img2: "http://localhost:4000/images/p56_2.jpg",
    img3: "http://localhost:4000/images/th6.jpeg",
    type: "Tea",
    category: "Flower",
    price: "400",
    description:
      "Jasmine Phoenix Pearls are perfumy, hand-rolled jewels of tea from Fuding, in Fujian province, China. Any fan of jasmine tea should try this specially crafted wonder. When added to hot water, Jasmine Phoenix Pearls majestically unfurl, releasing their delicate scent and flavor. Also known as 'Jasmine Dragon Pearls', their liquor is sweet and almost sugary. Very soft, airy mouthfeel. The delicate quality of the flavor is due in part to the leaves used to produce this tea: two tender, tiny new leaves and one plump unopened leaf bud. Younger leaves will yield softer flavor.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a25",
    id: 57,
    name: "irish breakfast",
    img1: "http://localhost:4000/images/p57_1.jpg",
    img2: "http://localhost:4000/images/p57_2.jpg",
    img3: "http://localhost:4000/images/eb1.jpg",
    type: "Tea",
    category: "English Breakfast",
    price: "500",
    description:
      "Our Irish Breakfast combines hearty black teas from Ceylon (Sri Lanka) and Assam (India) to get your morning off to a bright start. As its name implies, the Irish Breakfast black tea blend is an ideal accompaniment to a morning meal. It seamlessly blends the citrusy notes of a high-grown Ceylon with the malty underscore of a pungent Assam. Spicy and jammy aroma on the leaf, malty and deep flavor with a brisk and 'buzzy' mouthfeel. Rounded sweetness in the finish. May be enjoyed plain or with a drop of milk. Irish Breakfast is one of Adagio's most popular teas.",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a26",
    id: 58,
    name: "classic english breakfast",
    img1: "http://localhost:4000/images/p58_1.jpg",
    img2: "http://localhost:4000/images/p58_2.jpg",
    img3: "http://localhost:4000/images/eb2.jpg",
    type: "Tea",
    category: "English Breakfast",
    price: "600",
    description:
      "English Breakfast is a full-bodied black tea blend that goes well with a traditional English breakfast. The original cup was made with black Keemun tea from Anhui province in China. Across many generations, plenty of different interpretations of this famous blend have been made. Our English Breakfast stays close to the classic. Made from top quality black Keemun tea, prized for its rich, slightly smoky flavor and perfectly 'on point' astringency. Balanced, very honeyed aroma. May be enjoyed plain or with a drop of milk. This fine example of an English Breakfast remains one of Adagio's most popular varieties.",
    rating: [
      4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a27",
    id: 59,
    name: "scottish breakfast",
    img1: "http://localhost:4000/images/p59_1.jpg",
    img2: "http://localhost:4000/images/p59_2.jpg",
    img3: "http://localhost:4000/images/eb3.jpg",
    type: "Tea",
    category: "English Breakfast",
    price: "200",
    description:
      "Whether needed to wash down a full Scottish breakfast or to warm your bones after a walk on the misty moors, our Scottish Breakfast tea will do the trick. Richly blended with Assam, Keemun, Yunnan, and Sri Lankan full-leaf teas, you'll get a deep cup with malty notes, red fruitiness, hints of smoke and a touch of Yunnan pepperiness. Straight up or with a splash of cream, Scottish Breakfast is also a fine companion for your overdue Robbie Burns indulgence: 'O, my Luve is like a red, red rose, That's newly sprung in June. O, my Luve is like the melody, That's sweetly played in tune.'",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5,
    ],
    count: 7,
  },
  {
    _id: "65a0158ab2c30fad25a22a28",
    id: 60,
    name: "earl grey supreme",
    img1: "http://localhost:4000/images/p60_1.jpg",
    img2: "http://localhost:4000/images/p60_2.jpg",
    img3: "http://localhost:4000/images/eb4.jpg",
    type: "Tea",
    category: "English Breakfast",
    price: "300",
    description:
      "Earl Grey Supreme is a grand take on a well-loved classic for those who enjoy the timeless duet of tea and bergamot citrus. Blended with full-bodied Ceylon tea for body and boldness and rich Keemun to soften the edges and let the citrus shine. Then we added an extra splash of bergamot with sprinkle of Silver Needle white tea buds to add complexity and a delicate touch of white cornflower to further gild the lily. Earl Grey lovers, this next level tea is for you!",
    rating: [
      4, 5, 3, 4, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 3, 5, 5, 4, 5, 4, 5,
      4, 5, 4, 5, 4, 5, 4, 5, 2, 5, 5, 4,
    ],
    count: 7,
  },
];
